### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by bergie** [SignalK/instrumentpanel#109]
Many modern devices can support a dark mode with the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query. Adding dark styling to the instrument panel utilizing this would allow automatic switching to a more night vision friendly coloring at night time.

Quick-and-dirty option would be:

```css
@media (prefers-color-scheme: dark) {
  body {
    filter: invert(100%);
    background-color: #000;
  }
}
```

This would look like:
<img width="338" alt="Screenshot 2019-09-16 at 14 54 52" src="https://user-images.githubusercontent.com/3346/64959701-fabc1b00-d891-11e9-8d46-ff751a89673f.png">

<img width="513" alt="Screenshot 2019-09-16 at 14 56 05" src="https://user-images.githubusercontent.com/3346/64959771-263f0580-d892-11e9-9afb-2102f2baa235.png">

Of course one could design a nicer color scheme, too.

Relates to #30
